version: '3.8'
services:
  mysql-db:
    build:
      context: ./docker-files/database
    image: episodes-task-containers/episodes-task-database
    container_name: episodes-task-repo
    ports:
      -  "3306:3306"
    volumes:
      - episodes-task-data:/var/lib/mysql

  web-app:
    build:
      context: .
    image: episodes-task-containers/episodes-task-application
    container_name: episodes-task-app
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/episodes_task_db
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      
volumes:
  episodes-task-data: {}